"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Trash2, CheckCircle, XCircle, Star } from "@/lib/icons";
import { ConfirmActionDialog } from "@/components/admin/ConfirmActionDialog";

interface BulkActionsBarProps { selectedCount: number; onBulkDelete: () => void; onBulkPublish: () => void; onBulkUnpublish: () => void; onBulkSetFeatured: () => void; onBulkUnsetFeatured: () => void; onClearSelection: () => void; }
type PendingAction = { title: string; description: string; label: string; destructive?: boolean; action: () => void } | null;

export function BulkActionsBar({ selectedCount, onBulkDelete, onBulkPublish, onBulkUnpublish, onBulkSetFeatured, onBulkUnsetFeatured, onClearSelection }: BulkActionsBarProps) {
  const [pendingAction, setPendingAction] = useState<PendingAction>(null);
  if (selectedCount === 0) return null;
  const confirm = () => { pendingAction?.action(); setPendingAction(null); };
  return <><div className="flex items-center justify-between p-4 bg-secondary/50 border border-border/50 rounded-none"><div className="flex items-center gap-4"><span className="font-mono text-sm">{selectedCount} ARTICLE{selectedCount > 1 ? "S" : ""} SELECTED</span><Button variant="ghost" size="sm" onClick={onClearSelection} className="font-mono text-xs">CLEAR</Button></div><div className="flex items-center gap-2"><Button variant="outline" size="sm" onClick={() => setPendingAction({ title: "PUBLISH_ARTICLES", description: `Publish ${selectedCount} selected article(s) to the public blog?`, label: "PUBLISH", action: onBulkPublish })} className="font-mono text-xs rounded-none border-border/50"><CheckCircle className="w-4 h-4 mr-2" />PUBLISH</Button><Button variant="outline" size="sm" onClick={() => setPendingAction({ title: "UNPUBLISH_ARTICLES", description: `Move ${selectedCount} selected article(s) back to draft?`, label: "UNPUBLISH", action: onBulkUnpublish })} className="font-mono text-xs rounded-none border-border/50"><XCircle className="w-4 h-4 mr-2" />UNPUBLISH</Button><Button variant="outline" size="sm" onClick={() => setPendingAction({ title: "FEATURE_ARTICLES", description: `Feature ${selectedCount} selected article(s)?`, label: "FEATURE", action: onBulkSetFeatured })} className="font-mono text-xs rounded-none border-border/50"><Star className="w-4 h-4 mr-2" />FEATURE</Button><Button variant="outline" size="sm" onClick={() => setPendingAction({ title: "UNFEATURE_ARTICLES", description: `Remove featured state from ${selectedCount} selected article(s)?`, label: "UNFEATURE", action: onBulkUnsetFeatured })} className="font-mono text-xs rounded-none border-border/50"><Star className="w-4 h-4 mr-2" />UNFEATURE</Button><Button variant="destructive" size="sm" onClick={() => setPendingAction({ title: "DELETE_ARTICLES", description: `Delete ${selectedCount} selected article(s)? This action cannot be undone.`, label: "DELETE", destructive: true, action: onBulkDelete })} className="font-mono text-xs rounded-none"><Trash2 className="w-4 h-4 mr-2" />DELETE</Button></div></div><ConfirmActionDialog open={!!pendingAction} onOpenChange={(open) => !open && setPendingAction(null)} title={pendingAction?.title ?? "CONFIRM_ACTION"} description={pendingAction?.description ?? "Confirm this action."} confirmLabel={pendingAction?.label ?? "CONFIRM"} variant={pendingAction?.destructive ? "destructive" : "default"} onConfirm={confirm} /></>;
}
