# These are supported funding model platforms

github: [idugeni] # Replace with up to 4 GitHub Sponsors-enabled usernames
patreon: oldsoul # Replace with your Patreon username
open_collective: oldsoul # Replace with your Open Collective username
ko_fi: oldsoul # Replace with your Ko-fi username
tidelift: npm/oldsoul # Replace with a single Tidelift platform-name/package-name
community_bridge: # Replace with a single Community Bridge project-name
liberapay: oldsoul # Replace with your Liberapay username
issuehunt: idugeni # Replace with your IssueHunt username
otechie: oldsoul # Replace with your Otechie username
custom: ['https://saweria.co/oldsoul', 'https://trakteer.id/oldsoul'] # Replace with up to 4 custom sponsorship URLs