"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Eye, Star, Trash2, XCircle } from "@/lib/icons";
import { ConfirmActionDialog } from "@/components/admin/ConfirmActionDialog";

type PendingAction = { title: string; description: string; label: string; destructive?: boolean; action: () => Promise<void> } | null;

export function TestimonialBulkActionsBar({ selectedCount, onShow, onHide, onFeature, onUnfeature, onDelete, onClearSelection }: { selectedCount: number; onShow: () => Promise<void>; onHide: () => Promise<void>; onFeature: () => Promise<void>; onUnfeature: () => Promise<void>; onDelete: () => Promise<void>; onClearSelection: () => void }) {
  const [pendingAction, setPendingAction] = useState<PendingAction>(null);
  const [isPending, setIsPending] = useState(false);
  if (!selectedCount) return null;
  const confirm = async () => { if (!pendingAction) return; setIsPending(true); try { await pendingAction.action(); setPendingAction(null); } finally { setIsPending(false); } };
  return <><div className="flex flex-wrap items-center justify-between gap-3 border border-primary/30 bg-primary/5 p-3"><span className="font-mono text-xs text-primary">{selectedCount} TESTIMONIAL(S)_SELECTED</span><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" className="rounded-none font-mono" onClick={() => setPendingAction({ title: "SHOW_TESTIMONIALS", description: `Show ${selectedCount} selected testimonial(s) publicly?`, label: "SHOW", action: onShow })}><Eye className="mr-2 h-4 w-4" />SHOW</Button><Button variant="outline" size="sm" className="rounded-none font-mono" onClick={() => setPendingAction({ title: "HIDE_TESTIMONIALS", description: `Hide ${selectedCount} selected testimonial(s) from public pages?`, label: "HIDE", action: onHide })}><XCircle className="mr-2 h-4 w-4" />HIDE</Button><Button variant="outline" size="sm" className="rounded-none font-mono" onClick={() => setPendingAction({ title: "FEATURE_TESTIMONIALS", description: `Feature ${selectedCount} selected testimonial(s)?`, label: "FEATURE", action: onFeature })}><Star className="mr-2 h-4 w-4" />FEATURE</Button><Button variant="outline" size="sm" className="rounded-none font-mono" onClick={() => setPendingAction({ title: "UNFEATURE_TESTIMONIALS", description: `Remove featured state from ${selectedCount} selected testimonial(s)?`, label: "UNFEATURE", action: onUnfeature })}><XCircle className="mr-2 h-4 w-4" />UNFEATURE</Button><Button variant="destructive" size="sm" className="rounded-none font-mono" onClick={() => setPendingAction({ title: "DELETE_TESTIMONIALS", description: `Delete ${selectedCount} selected testimonial(s)? This action cannot be undone.`, label: "DELETE", destructive: true, action: onDelete })}><Trash2 className="mr-2 h-4 w-4" />DELETE</Button><Button variant="ghost" size="sm" className="rounded-none font-mono" onClick={onClearSelection}>CLEAR</Button></div></div><ConfirmActionDialog open={!!pendingAction} onOpenChange={(open) => !open && setPendingAction(null)} title={pendingAction?.title ?? "CONFIRM_ACTION"} description={pendingAction?.description ?? "Confirm this action."} confirmLabel={pendingAction?.label ?? "CONFIRM"} variant={pendingAction?.destructive ? "destructive" : "default"} isPending={isPending} onConfirm={confirm} /></>;
}
