"use client";

import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Search } from "@/lib/icons";

export interface TestimonialFiltersState { q?: string; visibility?: "visible" | "hidden"; featured?: "true" | "false"; rating?: number; sort?: "date" | "name" | "rating" | "featured" | "visibility"; order?: "asc" | "desc" }
export function TestimonialFilters({ filters }: { filters: TestimonialFiltersState }) {
  return <form action="/admin/testimonials" className="grid gap-3 rounded-none border border-border/50 bg-card/70 p-4 md:grid-cols-3 xl:grid-cols-7"><div className="relative xl:col-span-2"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input name="q" defaultValue={filters.q} placeholder="Search testimonials..." className="rounded-none pl-9 font-mono" /></div><Select name="visibility" defaultValue={filters.visibility || "all"}><SelectTrigger className="rounded-none font-mono"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">ALL_VISIBILITY</SelectItem><SelectItem value="visible">VISIBLE</SelectItem><SelectItem value="hidden">HIDDEN</SelectItem></SelectContent></Select><Select name="featured" defaultValue={filters.featured || "all"}><SelectTrigger className="rounded-none font-mono"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">ALL_FEATURED</SelectItem><SelectItem value="true">FEATURED</SelectItem><SelectItem value="false">NOT_FEATURED</SelectItem></SelectContent></Select><Select name="rating" defaultValue={filters.rating ? String(filters.rating) : "all"}><SelectTrigger className="rounded-none font-mono"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">ALL_RATING</SelectItem>{[5,4,3,2,1].map((rating) => <SelectItem key={rating} value={String(rating)}>{rating}_STAR</SelectItem>)}</SelectContent></Select><Select name="sort" defaultValue={filters.sort || "date"}><SelectTrigger className="rounded-none font-mono"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="date">DATE</SelectItem><SelectItem value="name">NAME</SelectItem><SelectItem value="rating">RATING</SelectItem><SelectItem value="featured">FEATURED</SelectItem><SelectItem value="visibility">VISIBILITY</SelectItem></SelectContent></Select><div className="flex gap-2"><Button type="submit" className="flex-1 rounded-none font-mono">FILTER</Button><Button asChild variant="outline" className="rounded-none font-mono"><Link href="/admin/testimonials">RESET</Link></Button></div><input type="hidden" name="order" value={filters.order || "desc"} /></form>;
}
