"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { CheckCircle, Eye, Trash2, XCircle } from "@/lib/icons";
import { ConfirmActionDialog } from "@/components/admin/ConfirmActionDialog";

interface MessageBulkActionsBarProps { selectedCount: number; onBulkRead: () => Promise<void>; onBulkUnread: () => Promise<void>; onBulkReplied: () => Promise<void>; onBulkUnreplied: () => Promise<void>; onBulkDelete: () => Promise<void>; onClearSelection: () => void; }
type PendingAction = { key: string; title: string; description: string; label: string; destructive?: boolean; action: () => Promise<void> } | null;

export function MessageBulkActionsBar({ selectedCount, onBulkRead, onBulkUnread, onBulkReplied, onBulkUnreplied, onBulkDelete, onClearSelection }: MessageBulkActionsBarProps) {
  const [pendingAction, setPendingAction] = useState<PendingAction>(null);
  const [loading, setLoading] = useState(false);
  if (selectedCount === 0) return null;
  const confirm = async () => { if (!pendingAction) return; setLoading(true); try { await pendingAction.action(); setPendingAction(null); } finally { setLoading(false); } };
  return <><div className="flex flex-wrap items-center justify-between gap-3 border border-primary/30 bg-primary/5 p-3"><span className="font-mono text-xs text-primary">{selectedCount} TRANSMISSION(S)_SELECTED</span><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" className="rounded-none font-mono" disabled={loading} onClick={() => setPendingAction({ key: "read", title: "MARK_MESSAGES_READ", description: `Mark ${selectedCount} selected transmission(s) as read?`, label: "MARK_READ", action: onBulkRead })}><Eye className="mr-2 h-4 w-4" /> MARK_READ</Button><Button variant="outline" size="sm" className="rounded-none font-mono" disabled={loading} onClick={() => setPendingAction({ key: "unread", title: "MARK_MESSAGES_UNREAD", description: `Mark ${selectedCount} selected transmission(s) as unread?`, label: "MARK_UNREAD", action: onBulkUnread })}><XCircle className="mr-2 h-4 w-4" /> MARK_UNREAD</Button><Button variant="outline" size="sm" className="rounded-none font-mono" disabled={loading} onClick={() => setPendingAction({ key: "replied", title: "MARK_MESSAGES_REPLIED", description: `Mark ${selectedCount} selected transmission(s) as replied?`, label: "MARK_REPLIED", action: onBulkReplied })}><CheckCircle className="mr-2 h-4 w-4" /> MARK_REPLIED</Button><Button variant="outline" size="sm" className="rounded-none font-mono" disabled={loading} onClick={() => setPendingAction({ key: "unreplied", title: "MARK_MESSAGES_UNREPLIED", description: `Mark ${selectedCount} selected transmission(s) as unreplied?`, label: "MARK_UNREPLIED", action: onBulkUnreplied })}><XCircle className="mr-2 h-4 w-4" /> MARK_UNREPLIED</Button><Button variant="destructive" size="sm" className="rounded-none font-mono" disabled={loading} onClick={() => setPendingAction({ key: "delete", title: "DELETE_TRANSMISSIONS", description: `Permanently delete ${selectedCount} contact message(s)? This action cannot be undone.`, label: "DELETE", destructive: true, action: onBulkDelete })}><Trash2 className="mr-2 h-4 w-4" /> DELETE</Button><Button variant="ghost" size="sm" className="rounded-none font-mono" onClick={onClearSelection}>CLEAR</Button></div></div><ConfirmActionDialog open={!!pendingAction} onOpenChange={(open) => !open && setPendingAction(null)} title={pendingAction?.title ?? "CONFIRM_ACTION"} description={pendingAction?.description ?? "Confirm this action."} confirmLabel={pendingAction?.label ?? "CONFIRM"} variant={pendingAction?.destructive ? "destructive" : "default"} isPending={loading} onConfirm={confirm} /></>;
}
