"use client";

import Image from "next/image";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import { Copy, Edit, Eye, FileCode, Globe, ImageIcon, MonitorUp, Star } from "@/lib/icons";
import { DeleteProjectButton } from "./DeleteProjectButton";
import { AdminTableActionButton } from "@/components/admin/AdminTableActionButton";
import { StatusPill } from "@/components/admin/StatusPill";

interface Project { id: string; nama: string; slug: string; deskripsi: string; kategori: string | null; status: "ongoing" | "completed" | "archived"; tech_stack: string[] | null; thumbnail_url: string | null; klien: string | null; tanggal_mulai: string | null; tanggal_selesai: string | null; github_url: string | null; live_url: string | null; featured: boolean; created_at: string }
interface ProjectTableProps { projects: Project[]; selectedIds: string[]; onSelectAll: (checked: boolean) => void; onSelectOne: (id: string, checked: boolean) => void; onPreview: (project: Project) => void; onDuplicate: (id: string) => void }
const getStatusTone = (status: Project["status"]) => {
  if (status === "completed") return "success";
  if (status === "ongoing") return "info";
  return "muted";
};
function dateRange(project: Project) { if (!project.tanggal_mulai && !project.tanggal_selesai) return null; return `${project.tanggal_mulai || "?"} → ${project.tanggal_selesai || "Now"}`; }

export function ProjectTable({ projects, selectedIds, onSelectAll, onSelectOne, onPreview, onDuplicate }: ProjectTableProps) {
  const allSelected = projects.length > 0 && selectedIds.length === projects.length;
  return <Table className="w-full table-fixed"><TableHeader><TableRow className="border-border/50 hover:bg-transparent"><TableHead className="w-11"><Checkbox checked={allSelected} onCheckedChange={onSelectAll} aria-label="Select all" className="rounded-none" /></TableHead><TableHead className="font-mono text-primary">PROJECT</TableHead><TableHead className="hidden w-[260px] font-mono text-primary xl:table-cell">METADATA</TableHead><TableHead className="w-[150px] text-right font-mono text-primary">ACTIONS</TableHead></TableRow></TableHeader><TableBody>{projects.length === 0 ? <TableRow><TableCell colSpan={4} className="py-8 text-center font-mono text-muted-foreground">NO_PROJECTS_FOUND</TableCell></TableRow> : projects.map((project) => <TableRow key={project.id} className="border-border/50 align-top hover:bg-secondary/40"><TableCell className="pt-5"><Checkbox checked={selectedIds.includes(project.id)} onCheckedChange={(checked) => onSelectOne(project.id, checked as boolean)} aria-label={`Select ${project.nama}`} className="rounded-none" /></TableCell><TableCell className="py-4"><div className="flex min-w-0 flex-col gap-4 sm:flex-row"><div className="relative h-28 w-full shrink-0 overflow-hidden border border-border/50 bg-secondary sm:h-24 sm:w-40">{project.thumbnail_url ? <Image src={project.thumbnail_url} alt={project.nama} fill sizes="(max-width: 640px) 100vw, 160px" className="object-cover" /> : <div className="flex h-full w-full items-center justify-center text-muted-foreground"><ImageIcon className="h-7 w-7" /></div>}</div><div className="min-w-0 flex-1 space-y-2"><div className="flex flex-wrap items-center gap-2">{project.featured && <Star className="h-4 w-4 shrink-0 fill-yellow-500 text-yellow-500" />}<h3 className="break-words font-mono text-base font-semibold leading-snug text-foreground">{project.nama}</h3></div><p className="break-all font-mono text-xs text-primary/80">/{project.slug}</p>                      {project.deskripsi && <p className="whitespace-normal break-words text-sm leading-relaxed text-muted-foreground">{project.deskripsi}</p>}<div className="flex flex-wrap gap-2">
                        <StatusPill tone={getStatusTone(project.status)}>
                          {project.status.toUpperCase()}
                        </StatusPill>
                        {project.kategori && <span className="border border-border/50 bg-secondary px-2 py-1 font-mono text-[11px]">{project.kategori}</span>}{project.klien && <span className="border border-border/50 px-2 py-1 font-mono text-[11px] text-muted-foreground">CLIENT: {project.klien}</span>}{dateRange(project) && <span className="border border-border/50 px-2 py-1 font-mono text-[11px] text-muted-foreground">{dateRange(project)}</span>}</div>{project.tech_stack && project.tech_stack.length > 0 && <div className="flex flex-wrap gap-1.5 pt-1">{project.tech_stack.map((tech) => <span key={tech} className="break-words border border-primary/20 bg-primary/10 px-2 py-1 font-mono text-[10px] text-primary">{tech}</span>)}</div>}<div className="grid gap-2 font-mono text-xs text-muted-foreground xl:hidden"><span>{project.kategori || "NO_CATEGORY"}</span><span>{project.klien || "NO_CLIENT"}</span>{dateRange(project) && <span>{dateRange(project)}</span>}</div></div></div></TableCell><TableCell className="hidden py-4 xl:table-cell"><div className="space-y-2 font-mono text-xs">
                  <div className="inline-block">
                    <StatusPill tone={getStatusTone(project.status)}>
                      {project.status.toUpperCase()}
                    </StatusPill>
                  </div>
                  <div className="break-words text-muted-foreground">Category: {project.kategori || "-"}</div><div className="break-words text-muted-foreground">Client: {project.klien || "-"}</div>{dateRange(project) && <div className="break-words text-muted-foreground">{dateRange(project)}</div>}<div className="flex flex-wrap gap-1.5 pt-1">{project.tech_stack?.map((tech) => <span key={tech} className="border border-primary/20 bg-primary/10 px-1.5 py-0.5 text-[10px] text-primary">{tech}</span>) || <span className="text-muted-foreground">-</span>}</div></div></TableCell><TableCell className="py-4 text-right"><div className="flex flex-wrap justify-end gap-1"><AdminTableActionButton label={`Preview ${project.nama}`} icon={Eye} intent="view" onClick={() => onPreview(project)} /><AdminTableActionButton label={`View ${project.nama} public page`} icon={Globe} intent="open" href={`/projects/${project.slug}`} target="_blank" />{project.live_url && <AdminTableActionButton label={`View ${project.nama} live demo`} icon={MonitorUp} intent="open" href={project.live_url} target="_blank" rel="noopener noreferrer" />}{project.github_url && <AdminTableActionButton label={`Open ${project.nama} repository`} icon={FileCode} intent="open" href={project.github_url} target="_blank" rel="noopener noreferrer" />}<AdminTableActionButton label={`Edit ${project.nama}`} icon={Edit} intent="edit" href={`/admin/projects/${project.slug}/edit`} /><AdminTableActionButton label={`Duplicate ${project.nama}`} icon={Copy} intent="duplicate" onClick={() => onDuplicate(project.id)} /><DeleteProjectButton projectId={project.id} projectName={project.nama} /></div></TableCell></TableRow>)}</TableBody></Table>;
}
