name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    name: Run ESLint Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: npm install --force eslint@9.9.1 --loglevel=error

      - name: Run ESLint
        run: npx eslint . --config .eslintrc.json --ext .js,.jsx,.ts,.tsx
        continue-on-error: true
